---
services:
  app-service:
    container_name: app-cont
    build:
      context: .
      dockerfile: Docker-app/Dockerfile
    restart: unless-stopped
    ports:
      - "9000:8080"
    depends_on:
      devopsdb:
        condition: service_healthy
    deploy:
      resources:
        reservations:
          cpus: "0.5"
          memory: 100M
        limits:
          cpus: "1.0"
          memory: 150M

  devopsdb:
    container_name: db-cont
    build: Docker-db/
    restart: unless-stopped
    volumes:
      - mysql-volume:/var/lib/mysql/
    env_file:
      - config.env 
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-pdevopspassword"]
      start_period: 30s
      interval: 20s
      timeout: 20s
      retries: 3
    deploy:
      resources:
        reservations:
          cpus: "0.5"
          memory: 150M
        limits:
          cpus: "1.0"
          memory: 300M

volumes:
  mysql-volume:
...
